#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times (while) 
# but with 3 stages (4th, 9th, 17th) iteration

i=1
while [ $i -le 20 ]
do
	echo $i
	
	if [ $i -eq 4 ]
	then
		echo "bad luck from China"
	elif [ $i -eq 9 ]
	then
		echo "bad luck from Japan"
	elif [ $i -eq 17 ]
	then
		echo "back luck from Italy"
	fi

	: $(( i++ ))
done
